version: 2.1

aliases:
  - &ci-build-image quay.io/yeebase/ci-build:7.3
  - &workspace_root ~/workspace

  - &save_composer_cache
    key: composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json" }}
    paths:
      - /composer/cache-dir

  - &restore_composer_cache
    keys:
      - composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json.ci" }}
      - composer-cache-v1-{{ .Branch }}-
      - composer-cache-v1-

  - &save_js_packages
    key: js-packages-v2-{{ .Branch }}-{{ checksum "neos-debug/e2e/package-lock.json" }}
    paths:
      - /root/.npm
      - /root/.cache/Cypress

  - &restore_js_packages
    keys:
      - js-packages-v2-{{ .Branch }}-{{ checksum "e2e/package-lock.json" }}
      - js-packages-v2-{{ .Branch }}-
      - js-packages-v2-

  - &attach_workspace
    at: *workspace_root

  - &persist_to_workspace
    root: .
    paths:
      - .

jobs:
  checkout:
    docker:
      - image: *ci-build-image
    environment:
      COMPOSER_CACHE_DIR: /composer/cache-dir
    steps:
      - checkout
      - restore_cache: *restore_composer_cache
      - restore_cache: *restore_js_packages

      - run: |
          mkdir neos-debug
          shopt -s extglob dotglob
          mv !(neos-debug) neos-debug
          shopt -u dotglob
          cp neos-debug/composer.json.ci composer.json
          cp neos-debug/phpcs.xml.dist phpcs.xml.dist
          composer update
          mkdir -p Configuration
          cp neos-debug/e2e/Settings.yaml Configuration/Settings.yaml

      - run: cd neos-debug/e2e && npm ci

      - save_cache: *save_composer_cache
      - save_cache: *save_js_packages
      - persist_to_workspace: *persist_to_workspace

  lint:
    working_directory: *workspace_root
    docker:
      - image: *ci-build-image
    steps:
      - attach_workspace: *attach_workspace
      - run: bin/phpcs neos-debug/Classes

  e2e:
    working_directory: *workspace_root
    environment:
      FLOW_CONTEXT: Production
    docker:
      - image: *ci-build-image
      - image: circleci/mariadb:10.2
        environment:
          MYSQL_DATABASE: neos-debug
          MYSQL_ROOT_PASSWORD: some-password
    steps:
      - attach_workspace: *attach_workspace
      - restore_cache:
          keys:
            - js-packages-v2-{{ .Branch }}-{{ checksum "neos-debug/e2e/package-lock.json" }}
            - js-packages-v2-{{ .Branch }}-
            - js-packages-v2-

      - run: |
          ./flow flow:cache:flush
          ./flow flow:cache:warmup
          ./flow doctrine:migrate
          ./flow resource:publish
          ./flow site:import --package-key Neos.Demo
      - run:
          name: Start flow server
          command: ./flow server:run --port 8081
          background: true
      - run: cd neos-debug/e2e && npm run cy

      - store_artifacts:
          path: neos-debug/e2e/cypress/videos
      - store_artifacts:
          path: neos-debug/e2e/cypress/screenshots
      - store_artifacts:
          path: Data/Logs

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /dependabot.*/
      - lint:
          requires:
            - checkout
      - e2e:
          requires:
            - checkout

  build_and_test_dependabot:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only: /dependabot.*/
      - checkout:
          requires:
            - hold
      - lint:
          requires:
            - checkout
      - e2e:
          requires:
            - checkout
