t3n:
  Neos:
    Debug:
      enabled: false
      sql:
        # Set when a query should be considered as slow query. In ms
        slowQueryAfter: 10

Neos:
  Neos:
    fusion:
      autoInclude:
        't3n.Neos.Debug': true
