t3n:
  Neos:
    Debug:
      enabled: true
      sql:
        # Set when a query should be considered as slow query. In ms
        slowQueryAfter: 1

Neos:
  Neos:
    fusion:
      autoInclude:
        't3n.Neos.Debug': true
